.\" Copyright (c) 2010 Todd T. Fries <todd@fries.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt QRUN 1
.Os
.Sh NAME
.Nm qrun
.Nd wrapper to run qemu via simplistic user friendly arguments, building
knowledge of
.Xr qemu 1
into this script instead of unwieldy README documents.
.Sh SYNOPSIS
.Nm qrun
.Fl i
.Op Fl bCcMmnopsuv [\fI - [\fIqemu-options\fR]\fR]
.Sh DESCRIPTION
.Nm
requires at least the
.Fl i
option to specify the disk image.
If a file does not exist, it will be created.
.Pp
By default, user mode network emulation will be used, so no further
options are required for quick start usage.
See the
.Sx EXAMPLES
section below for other simple usages.
.Pp
The options
.Fl b ,
.Fl n ,
.Fl o ,
and
.Fl u
require
.Nm
to be executed as root, since they utilize priveleged operations.
.Pp
The options are as follows:
.Bl -tag -width A
.It Fl b Ar interface
If given, the
.Fl b
option specifies the bridge interface to bridge to a guest network
interface.
If used multiple times, a new guest network interface will be created
for each instance, bridged to the network interfaces in the order specified.
.It Fl C Ar path
If given, the
.Fl C
option specifies the cdrom image or device from which to read blocks of data
when presenting the guest os with a simulated
.Xr atapiscsi 4
cdrom device.
.It Fl c Ar path
If given, the
.Fl c
option specifies the same as the
.Fl C
option, but additionally boots the guest os from the simulated cdrom device.
.It Fl i Ar path
The
.Fl i
option specifies the file or device from which to read blocks of data
when presenting the guest os with a simulated
.Xr wd 4
device.
.It Fl M Ar mode
If specified, the
.Fl mode
can change the machine presented to the guest os.
By default, an i386 machine is presented.
The only other valid mode is amd64.
(Lowercase
.It Fl m Ar memsize
If specified, the
.Fl memsize
argument alters the memory presented to the guest os.
By default,
.Fl memsize
is 
.Dq 128m .
.It Fl n Ar string
If specified, the
.Fl n
option is a string passed to
.Xr ifconfig 8
to configure the
.Xr tun 4
device.
This is for routing
.Xr qemu 1
sessions natively and/or nating them via
.Xr pf 4 .
Like the
.Fl b
option, multiple
.Fl n
options may be specified, each one coinciding with an interface presented
to the guest os, in the order specified.
The
.Fl n
and
.Fl b
options may be both used if desired.
.It Fl p Ar path
If specified, the
.Fl path
option specifies the tftpboot dir from which to pxeboot the guest os.
The guest virtual machines bios will tftp the file
.Dq pxeboot
from the
.Fl path
specified and start executing it as a real system would.
.It Fl s Ar size
If specified, the
.Fl s
option specifies the size of the disk image to create, if 
.Nm
is auto-creating the disk image.
.It Fl u Ar user
If specified,
.Xr qemu 1
will be run as user
.Fl user .
This is recommended if one of the options requiring root privileges is
used, as the environment will be setup then the fdpass program will drop
privileges to the user specified and qemu will not be running as root.
.It Fl o Ar [\fI bridge=interface,model=nicmodel,macaddr=52:54:01:00:XX:XX \fR]
.It Fl o Ar [\fI netcfg=string,model=nicmodel,macaddr=52:54:01:00:XX:XX \fR]
.It Fl o Ar [\fI console=com0,monitor=stdio,serial=stdio \fR]
The
.Fl o
option if specified, presents a more advanced usage of the
.Fl b
and
.Fl n
options as well as enabling a serial console to be presented at a terminal
prompt.
If combined with the
.Fl p
option and an etc/boot.conf file containing
.Dq set tty com0
a system may be booted to a serial console in a terminal without requiring
graphics.
This can be especially useful for running inside
.Xr tmux 1 .
.Fl v
If specified, the
.Fl v
option presents verbose information while setting up
.Xr bridge 4
and
.Xr tun 4
interfaces as well as showing the
.Xr qemu 1
command line used when starting qemu.
.El
.Sh ENVIRONMENT
No environment variables are useful at this time.
.Sh EXAMPLES
Here are examples on how to use
.Nm .
.Pp
The most basic simple usage would be to install a guest os with user mode
networking:
.Dl $ qrun -i test.hd -c cd47.iso
After the installation, one would issue
.Dq quit
at the
.Dq (qemu)
prompt and then start
.Xr qemu 1
subsequent times via:
.Dl $ qrun -i test.hd
.Pp
.Sh SEE ALSO
.Xr qemu 1 ,
.Xr fdpass 1 ,
.Xr bridge 4,
.Xr pf 4,
.Xr tun 4
.Sh STANDARDS
Are there any standards to quote?
.Sh HISTORY
This utility is entirely a new creation from Todd T. Fries <todd@fries.net>,
inspired by Bob Beck <beck@openbsd.org>.
