.\" Copyright (c) 2010 Todd T. Fries <todd@fries.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt QRUN 1
.Os
.Sh NAME
.Nm qrun
.Nd qemu wrapper
.Sh SYNOPSIS
.Nm qrun
.Fl i Ar path
.Op Fl v
.Op Fl b Ar interface
.Op Fl C Ar path
.Op Fl c Ar path
.Op Fl M Ar mode
.Op Fl m Ar memsize
.Op Fl n Ar string
.Op Fl o Cm bridge \*(Ba console \*(Ba netcfg
.Op Fl p Ar path
.Op Fl s Ar size
.Op Fl u Ar user
.Op Ar qemu-options
.Sh DESCRIPTION
.Nm
requires at least the
.Fl i
option to specify the disk image.
If a file does not exist, it will be created.
.Pp
By default, user mode network emulation will be used, so no further
options are required for quick start usage.
See the
.Sx EXAMPLES
section below for other simple usages.
.Pp
The options
.Fl b ,
.Fl n ,
.Fl o ,
and
.Fl u
require
.Nm
to be executed as root, since they utilize privileged operations.
.Pp
The options are as follows:
.Pp
.Bl -tag -width Ds -compact
.It Fl b Ar interface
Specifies the
.Xr bridge 4
interface to bridge to a guest network interface.
If used multiple times, a new guest network interface will be created
for each instance, bridged to the network interfaces in the order specified.
.Pp
.It Fl C Ar path
Specifies the CD-ROM image or device from which to read blocks of data
when presenting the guest OS with a simulated
.Xr atapiscsi 4
CD-ROM device.
.Pp
.It Fl c Ar path
Identical to the
.Fl C
option, but additionally boots the guest OS from the simulated CD-ROM device.
.Pp
.It Fl i Ar path
Specifies the file or device from which to read blocks of data
when presenting the guest OS with a simulated
.Xr wd 4
device.
.Pp
.It Fl M Ar mode
Changes the machine presented to the guest OS.
By default, an i386 machine is presented.
The only other valid mode is amd64.
.Pp
.It Fl m Ar memsize
Alters the memory presented to the guest OS.
By default,
.Ar memsize
is 128m.
.Pp
.It Fl n Ar string
A string passed to
.Xr ifconfig 8
to configure the
.Xr tun 4
device.
This is for routing
.Xr qemu 1
sessions natively and/or NAT-ing them via
.Xr pf 4 .
Like the
.Fl b
option, multiple
.Fl n
options may be specified, each one coinciding with an interface presented
to the guest OS, in the order specified.
The
.Fl n
and
.Fl b
options may be both used if desired.
.Pp
.It Fl o Ar bridge=interface,model=nicmodel,macaddr=52:54:01:00:XX:XX
.It Fl o Ar netcfg=string,model=nicmodel,macaddr=52:54:01:00:XX:XX
.It Fl o Ar console=com0,monitor=stdio,serial=unix,vnc=[::]:3
.It Fl o Ar controllertype=<ctype>
Provides a more advanced usage of the
.Fl b
and
.Fl n
options as well as enabling a serial console to be presented at a terminal
prompt.
<ctype> can be one of
.Pp
.It Ar ahci
.It Ar isa-ide
.It Ar lsi53c895a
.It Ar virtio-blk-pci
.It Ar usb-storage
If combined with the
.Fl p
option and an
.Pa /etc/boot.conf
file containing
.Dq set tty com0 ,
a system may be booted to a serial console in a terminal without requiring
graphics.
This can be especially useful for running inside
.Xr tmux 1 .
.Pp
The
.Ar interface
option to bridge may be a physical interface, such as em0, or a special
notation:
.Bd -literal -offset indent
.Ar group:string
.Ed
.Pp
This special notation permits multiple qrun instances to be bridged together,
by adding the string to the interface group of the
.Xr bridge 4
instead of bridging to a physical interface.
This mainly for the
.Xr qnet 1
script, but advanced users may choose to use it themselves.
The string is limited by interface group limitations and therefore
may not end in a number.
.Pp
.It Fl p Ar path
Specifies the tftpboot dir from which to
.Xr pxeboot 8
the guest OS.
The guest virtual machines BIOS will TFTP the file
.Dq pxeboot
from the
.Ar path
specified and start executing it as a real system would.
.Pp
.It Fl s Ar size
Specifies the size of the disk image to create, if
.Nm
is auto-creating the disk image.
.Pp
.It Fl u Ar user
Runs
.Xr qemu 1
as user
.Ar user .
This is recommended if one of the options requiring root privileges is
used, as the environment will be set up then the fdpass program will drop
privileges to the user specified and qemu will not be running as root.
.Pp
.It Fl v
Provides verbose information while setting up
.Xr bridge 4
and
.Xr tun 4
interfaces as well as showing the
.Xr qemu 1
command line used when starting qemu.
.El
.Sh ENVIRONMENT
No environment variables are useful at this time.
.Sh EXAMPLES
Here are examples on how to use
.Nm .
.Pp
The most basic simple usage would be to install a guest OS with user mode
networking:
.Pp
.Dl $ qrun -i test.hd -c cd47.iso
.Pp
After the installation, one would issue
.Dq quit
at the
.Dq (qemu)
prompt and then start
.Xr qemu 1
subsequently via:
.Pp
.Dl $ qrun -i test.hd
.Pp
Another common way to use
.Nm
would be to bridge the native Ethernet to a
.Xr qemu 1
guest's network interface:
.Pp
.Dl $ sudo qrun -u $USER -i test.hd -b em0
.Pp
This sets up a
.Xr bridge 4
interface to connect the
.Xr em 4
interface of the native system and the
.Xr tun 4
interface of the
.Xr qemu 1
guest OS.
.Pp
The third common way to use
.Nm
would be to route the
.Xr qemu 1
guest's network interface:
.Pp
.Dl $ sudo qrun -u $USER -i test.hd -n 10.0.1.1/24
.Pp
This would set up a
.Xr tun 4
interface with
.Dq 10.0.1.1 netmask 255.255.255.0
and it would be up to the user to run
.Xr dhcpd 8
on the
.Xr tun 4
interface connected to the
.Xr qemu 1
guest OS.
.Pp
One final advanced example that most people will not want to bother with but
can show the power of
.Nm :
.Bd -literal -offset indent
$ sudo qrun -u $USER -i `pwd`/test.hd \e
  -o bridge=em0,model=rtl8139,macaddr=52:54:01:00:XX:XX \e
  -o console=com0 \e
  -- \e
  -serial telnet:127.0.0.1:30000,server,nowait \e
  -monitor telnet:127.0.0.1:40000,server,nowait \e
  -daemonize
.Ed
.Sh SEE ALSO
.Xr fdpass 1 ,
.Xr qemu 1 ,
.Xr bridge 4 ,
.Xr pf 4 ,
.Xr tun 4
.Sh HISTORY
This utility is entirely a new creation from
.An Todd T. Fries Aq todd@fries.net ,
inspired by
.An Bob Beck Aq beck@openbsd.org .
